# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    pers.learn: debug
    org.springframework: warn

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mappers/**/*.xml
  typeAliasesPackage: pers.learn.**.entity

spring:
  application:
    name: learn-java
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  datasource:
    db1:
      jdbc-url: jdbc:p6spy:mysql://localhost:3306/learning_java?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      password: ""
      username: root
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    # 使用mysql-connector-java包
    # driverClassName:com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      format_sql: true
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  profiles:
    active: dev
  redis:
    database: 15
    host: 127.0.0.1
    port: 6379

swagger:
  enabled: false
